"""Model access, image IO, and SVCP-format result recording.

This is the only module coupled to the model and the filesystem; the
verification maths lives in metrics.py and corruptions.py.
"""

from __future__ import annotations

import datetime
import hashlib
import json
import random
from pathlib import Path

import cv2
import numpy as np

from . import config as C
from . import traceability

_MODEL = None


def load_model():
    """Load the model under test once and cache it."""
    global _MODEL
    if _MODEL is None:
        from ultralytics import YOLO

        _MODEL = YOLO(str(C.MODEL_PATH))
    return _MODEL


def device_name() -> str:
    """Human-readable name of the inference device (for the results header)."""
    import torch

    if isinstance(C.DEVICE, int) and torch.cuda.is_available():
        return torch.cuda.get_device_name(C.DEVICE)
    return "cpu"


def ensure_dataset_yaml() -> Path:
    """Write a portable Ultralytics data YAML (absolute paths) from config.

    Generated at runtime so the repo carries no machine-specific path.
    """
    names = "\n".join(f"  {i}: {n}" for i, n in C.CLASS_NAMES.items())
    C.DATASET_YAML.parent.mkdir(parents=True, exist_ok=True)
    C.DATASET_YAML.write_text(
        "# Auto-generated by the verification harness - do not commit or edit.\n"
        f"path: {C.DATA}\n"
        "train: images/val\n"  # required by Ultralytics but unused (val-only harness)
        "val: images/val\n"
        f"names:\n{names}\n"
    )
    return C.DATASET_YAML


def val_images(n: int | None = None, seed: int = C.SEED):
    """Sorted validation image paths, optionally a deterministic sample of `n`."""
    imgs = sorted(C.VAL_IMAGES.glob("*"))
    if n is not None and n < len(imgs):
        imgs = sorted(random.Random(seed).sample(imgs, n), key=lambda p: p.stem)
    return imgs


def read_rgb(path) -> np.ndarray:
    return cv2.cvtColor(cv2.imread(str(path), cv2.IMREAD_COLOR), cv2.COLOR_BGR2RGB)


def predict(model, image, **kw):
    """Run inference on a path or RGB ndarray; return the Ultralytics OBB result."""
    src = image[:, :, ::-1] if isinstance(image, np.ndarray) else image  # RGB->BGR for arrays
    return model.predict(
        src,
        imgsz=C.IMGSZ,
        conf=C.CONF,
        iou=C.IOU,
        max_det=C.MAX_DET,
        device=C.DEVICE,
        verbose=False,
        **kw,
    )[0]


def dets_of(result) -> dict:
    """Black-box view of a detection result: count, confidences, class ids."""
    obb = result.obb
    if obb is None or obb.conf is None or len(obb.conf) == 0:
        return {"n": 0, "max_conf": 0.0, "mean_conf": 0.0, "cls": [], "conf": []}
    conf = obb.conf.cpu().numpy().astype(float)
    return {
        "n": int(len(conf)),
        "max_conf": float(conf.max()),
        "mean_conf": float(conf.mean()),
        "cls": obb.cls.cpu().numpy().astype(int).tolist(),
        "conf": conf.tolist(),
    }


def md5(path, chunk: int = 1 << 20) -> str:
    h = hashlib.md5()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(chunk), b""):
            h.update(block)
    return h.hexdigest()


def now() -> str:
    return datetime.datetime.now().strftime("%Y-%m-%d %H:%M")


# ----------------------------------------------------------------- result recording
_RESULTS: list[dict] = []


def record(tc_id, name, status, criteria, measured: dict, observations="", evidence=None):
    """Record one test-case result and persist its evidence JSON under results/<tc_id>/."""
    row = {
        "tc_id": tc_id,
        "name": name,
        "trace": traceability.trace_for(tc_id),
        "status": status,
        "criteria": criteria,
        "measured": measured,
        "observations": observations,
        "evidence": evidence or [],
        "run_date": now(),
    }
    case_dir = C.RESULTS / tc_id
    case_dir.mkdir(parents=True, exist_ok=True)
    (case_dir / "result.json").write_text(json.dumps(row, indent=2))
    _RESULTS.append(row)
    print(f"  [{status}] {tc_id}  {name}")
    return row


def results() -> list[dict]:
    return _RESULTS


def save_json(obj, path):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text(json.dumps(obj, indent=2))
